CREATE TABLE IF NOT EXISTS migrations (

    id INT AUTO_INCREMENT PRIMARY KEY,

    version VARCHAR(255) NOT NULL,

    name VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);